### ISSUE TITLE
跑起来是跑起来了，用户名是：mcloud-user 吧？，但还是没登录成功

### ISSUE THREAD

**Issue by duan847** [heyuxian/mcloud-oauth2-server#10]
![image](https://user-images.githubusercontent.com/13334549/34402718-7249b274-ebde-11e7-8c47-81f45879046d.png)

**Comment by heyuxian** [comment]
用户名： mcloud-user
密码： 123456
请尝试直接使用此用户登录后台管理页面： http://localhost:8043/uaa/login
如果登陆失败，请执行 flyway 命令重新初始化数据库
